### ISSUE TITLE
Registration: pathogen_prok_external/pathogen_cgps_track

### ISSUE THREAD

**Issue by magnusmanske** [sanger-pathogens/sapp#4]
No differentiation between `pathogen_prok_external` and `pathogen_cgps_track` in `bacteria_register_and_qc_study` ([see here](http://mediawiki.internal.sanger.ac.uk/index.php/Registering_data_with_the_Sequencing_Pipelines))

**Comment by puethe** [comment]
Only "internal" studies should use SAPP (for now). So no need to worry about `pathogen_prok_external`.
